### ISSUE TITLE
Delete entries from DB

### ISSUE THREAD

**Issue by mirellasprenger** [springernature/snics-employee#297] opened 2019-04-17 09:22 UTC
Harshad, could you please proceed with the deletion of the entries attached? Thanks.

Email from Stephanie:
![image](https://user-images.githubusercontent.com/43644896/56276435-c554ab00-6102-11e9-8126-c9f0b50f8480.png)
[Preeti for deletion_SNICS.xlsx](https://github.com/springernature/snics-employee/files/3088792/Preeti.for.deletion_SNICS.xlsx)

**Comment by karentom** [comment] 2019-04-18 10:02
@harshadporwal Confirmed with Steph that we should add a delete button on the management portal to delete the records from SNICS. This button should only be available to the admin role.

**Comment by harshadporwal** [comment] 2019-04-23 12:04
@karentom @mirellasprenger Opened the same ticket in management portal to add delete functionality.
https://github.com/springernature/snics-management/issues/374

**Comment by karentom** [comment] 2019-05-06 01:21
@harshadporwal @mirellasprenger Closing this since we have 374 in the management portal. Deletion of entries will be handled by RCO.

**Comment by karentom** [comment] 2019-05-06 01:24
@harshadporwal In the text box to confirm deletion, please add the following text:

"Are you sure you want to delete the Partner? The Partner will be deleted from SNICS but the SAP record will still exist (if it has been created in SAP). Check with snics@springernature.com  to see if the Partner should also be deleted in SAP."

**Closed** 2019-05-06 01:24 UTC
